import Head from 'next/head';

export default function Home() {

  return (
    <>

      <Head>
        <title>HackLink</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" type="image/jpg" href="images/logo.jpg" />
      </Head>
    
      <div>
        Body
      </div>
      
    </>
  );
}
